<?php

return [
    ['id' => 1,
        'english_name' => 'Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    ['id' => 2,
        'english_name' => 'Americas',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    ['id' => 3,
        'english_name' => 'Antarctica',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    ['id' => 4,
        'english_name' => 'Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    ['id' => 5,
        'english_name' => 'Europe',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    ['id' => 6,
        'english_name' => 'Oceania',
        'created_at' => now(),
        'updated_at' => now(),
    ],
];
