<?php

return [
    [
        'id' => 1,
        'continent_id' => 1,
        'english_name' => 'Eastern Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 2,
        'continent_id' => 1,
        'english_name' => 'Middle Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 3,
        'continent_id' => 1,
        'english_name' => 'Northern Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 4,
        'continent_id' => 1,
        'english_name' => 'Southern Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 5,
        'continent_id' => 1,
        'english_name' => 'Western Africa',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'id' => 7,
        'continent_id' => 2,
        'english_name' => 'Caribbean',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 8,
        'continent_id' => 2,
        'english_name' => 'Central America',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 9,
        'continent_id' => 2,
        'english_name' => 'Northern America',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 10,
        'continent_id' => 2,
        'english_name' => 'South America',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'id' => 6,
        'continent_id' => 3,
        'english_name' => 'Antarctica',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 11,
        'continent_id' => 4,
        'english_name' => 'Central Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 12,
        'continent_id' => 4,
        'english_name' => 'Eastern Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 13,
        'continent_id' => 4,
        'english_name' => 'South-Eastern Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 14,
        'continent_id' => 4,
        'english_name' => 'Southern Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 15,
        'continent_id' => 4,
        'english_name' => 'Western Asia',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'id' => 16,
        'continent_id' => 5,
        'english_name' => 'Eastern Europe',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 17,
        'continent_id' => 5,
        'english_name' => 'Northern Europe',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 18,
        'continent_id' => 5,
        'english_name' => 'Southern Europe',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 19,
        'continent_id' => 5,
        'english_name' => 'Western Europe',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'id' => 20,
        'continent_id' => 6,
        'english_name' => 'Australia and New Zealand',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 21,
        'continent_id' => 6,
        'english_name' => 'Melanesia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 22,
        'continent_id' => 6,
        'english_name' => 'Micronesia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => 23,
        'continent_id' => 6,
        'english_name' => 'Polynesia',
        'created_at' => now(),
        'updated_at' => now(),
    ],
];
